{"name": "test_exclude_domains_limit_enforced_151_raises", "status": "skipped", "statusDetails": {"message": "XFAIL In Document its mentioned as Max 150 , but in message it is Max 130\n\nAssertionError: assert 'Invalid valu... are allowed.' == 'Invalid valu... are allowed.'\n  \n  - Invalid value for exclude_domains. Max 150 domains are allowed.\n  ?                                         ^\n  + Invalid value for exclude_domains. Max 130 domains are allowed.\n  ?                                         ^", "trace": "@pytest.mark.negative\n    @pytest.mark.xfail(reason = \"In Document its mentioned as Max 150 , but in message it is Max 130\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_exclude_domains_limit_enforced_151_raises():\n        big_list = [f\"site{i}.com\" for i in range(151)]\n        payload = {\"query\": \"Cristiano Ronaldo\", \"exclude_domains\": big_list}\n>       assert_tavily_exception_error(payload,exception_messages[\"excludeDomainMaxLimit\"],BadRequestError)\n\ntest_tavily_api.py:627: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npayload = {'exclude_domains': ['site0.com', 'site1.com', 'site2.com', 'site3.com', 'site4.com', 'site5.com', ...], 'query': 'Cristiano Ronaldo'}\nexpected_error_msg = 'Invalid value for exclude_domains. Max 150 domains are allowed.', exception_name = <class 'tavily.errors.BadRequestError'>\n\n    def assert_tavily_exception_error(payload, expected_error_msg,exception_name: Type[BaseException] = BadRequestError):\n            with pytest.raises(exception_name) as exc:\n                tavily.search(**payload)\n            print(\"Error:\", str(exc.value))\n>           assert str(exc.value) == expected_error_msg\nE           AssertionError: assert 'Invalid valu... are allowed.' == 'Invalid valu... are allowed.'\nE             \nE             - Invalid value for exclude_domains. Max 150 domains are allowed.\nE             ?                                         ^\nE             + Invalid value for exclude_domains. Max 130 domains are allowed.\nE             ?                                         ^\n\ntest_tavily_api.py:704: AssertionError"}, "start": 1754785443513, "stop": 1754785444630, "uuid": "1de33647-ec17-447d-87aa-15d418c36cbd", "historyId": "8ce7a2b5a100f283601ffcce19e6bb26", "testCaseId": "8ce7a2b5a100f283601ffcce19e6bb26", "fullName": "test_tavily_api#test_exclude_domains_limit_enforced_151_raises", "labels": [{"name": "epic", "value": "Tavily Search API"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='In Document its mentioned as Max 150 , but in message it is Max 130')"}, {"name": "tag", "value": "negative"}, {"name": "suite", "value": "test_tavily_api"}, {"name": "host", "value": "DESKTOP-FTL2TTS"}, {"name": "thread", "value": "16220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tavily_api"}], "links": [{"type": "link", "url": "https://docs.tavily.com/documentation/api-reference/endpoint/search", "name": "API Reference"}]}